#
# Editing this file can easily break things. Be prepared.
#

# personal

author: Melton Zheng
bio: "Student"
description: "This is my blog"
email: meltonzheng@gmail.com
integrations: # Values here will be instered as USERNAME
  disqus: meltonzheng
  github: meltonzheng
  gcse: # https://cse.google.com/
  medium: meltonzheng # https://medium.com/@USERNAME
  rss: feed # check site-url/feed.xml
  twitter: meltonzheng
  youtube: meltonzheng # https://www.youtube.com/user/USERNAME/videos
location: Los Angeles
name: Melton Zheng

# site

baseurl: ""
collections:
  pages:
    output: true
    permalink: /:title/
  tags:
    output: true
    permalink: /:path/
  years:
    output: true
    permalink: /:path/
cover: images/timers.jpg
future: true
defaults:
  -
    scope:
      path: ""
    values:
      image: melton-profile-white.jpg
      layout: post
  -
    scope:
      path: _pages
      type: pages
    values:
      image: placeholder.jpg
      layout: post
  -
    scope:
      path: _posts
      type: posts
    values:
      featured: false
      image: placeholder.jpg
      layout: post
  -
    scope:
      path: _tags
      type: tags
    values:
      layout: list
      type: tags
  -
    scope:
      path: _years
      type: years
    values:
      layout: list
      type: years
domain: meltonzheng.github.io
encoding: utf-8
excerpt_separator: "\n\n"
highlighter: rouge
kramdown:
  input: GFM
lang: en
locale: en
markdown: kramdown
markdown_ext: md
permalink: /:title/
placeholder: images/placeholder.jpg
profile: images/melton-profile-white.jpg
timezone: UTC #America/Los_Angeles
title: Melton Zheng's Blog
title_separator: "-"
url: https://meltonzheng.github.io

# build

exclude:
  - .editorconfig
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jemoji
